### ISSUE TITLE
Key error when using deconv

### ISSUE THREAD

**Issue by akshay-antony** [mit-han-lab/torchsparse#156] opened 2022-06-06 22:03 UTC
/lib/python3.7/site-packages/torchsparse/nn/functional/conv.py", line 134, in conv3d
    kmap = input.kmaps[(tensor_stride, kernel_size, stride, dilation)]
KeyError: ((8, 8, 2), (3, 3, 3), (2, 2, 2), (1, 1, 1))

I am writing Cylinder3d using torchsparse, but a stride 2 deconv is causing key error. And is there a way to share the coordinate mapping Minkowski or spconv?

**Comment by zhijian-liu** [comment] 2022-06-25 01:03
@akshay-antony, thank you for reporting this issue! Could you please provide a short code snippet to reproduce this bug?

**Comment by zhijian-liu** [comment] 2023-07-15 01:31
Since TorchSparse has been upgraded to v2.1.0, could you please attempt to install the latest version? I will now close this issue, but please don't hesitate to reopen it if the problem persists.

**Closed by zhijian-liu** 2023-07-15 01:31 UTC
